version: '3'

services:
  source_postgres:
    image: postgres:14-alpine
    ports:
      - "5434:5432"
    networks:
      - elt_network
    environment:
      POSTGRES_DB: ${POSTGRES_SOURCE_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - ./source_db_init/init.sql:/docker-entrypoint-initdb.d/init.sql
  
  destination_postgres:
    image: postgres:14-alpine
    ports:
      - "5435:5432"
    networks:
      - elt_network
    environment:
      POSTGRES_DB: ${POSTGRES_DESTINATION_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}

  elt_script:
    build: 
      context: ./elt
      dockerfile: Dockerfile
    command: [ "python", "elt_script.py" ]
    networks:
      - elt_network
    depends_on:
      - source_postgres
      - destination_postgres

networks:
  elt_network:
    driver: bridge